import type { UserRole } from "@nexus/codex-models";

/** 메뉴 코드 상수 — 권한 관리용 */
export const CODEX_MENU_CODES = {
  DASHBOARD: "DASHBOARD",
  EXPLORER: "EXPLORER",
  NEW_REQUEST: "NEW_REQUEST",
  COMMON_CODES_VIEW: "COMMON_CODES_VIEW",
  APPROVALS: "APPROVALS",
  GOVERNANCE: "GOVERNANCE",
  AUDIT: "AUDIT",
  VALIDATIONS: "VALIDATIONS",
  VALIDATION_DETAIL: "VALIDATION_DETAIL",
  ADMIN_COMMON_CODES: "ADMIN_COMMON_CODES",
  ADMIN_USERS: "ADMIN_USERS",
  ADMIN_PERMISSIONS: "ADMIN_PERMISSIONS",
  ADMIN_SYSTEM_CODES: "ADMIN_SYSTEM_CODES",
  ADMIN_DB_SETTINGS: "ADMIN_DB_SETTINGS",
} as const;

export type MenuCode = (typeof CODEX_MENU_CODES)[keyof typeof CODEX_MENU_CODES];

/**
 * 역할별 접근 가능 메뉴 매트릭스
 * UX 명세 §3.3 역할별 접근 권한 테이블 기준
 */
const M = CODEX_MENU_CODES;

export const ROLE_MENU_ACCESS: Record<UserRole, readonly MenuCode[]> = {
  SYSTEM_ADMIN: [
    M.DASHBOARD, M.EXPLORER, M.NEW_REQUEST, M.COMMON_CODES_VIEW,
    M.APPROVALS, M.GOVERNANCE, M.AUDIT, M.VALIDATIONS, M.VALIDATION_DETAIL,
    M.ADMIN_COMMON_CODES, M.ADMIN_USERS, M.ADMIN_PERMISSIONS,
    M.ADMIN_SYSTEM_CODES, M.ADMIN_DB_SETTINGS,
  ],
  REVIEWER_APPROVER: [
    M.DASHBOARD, M.EXPLORER, M.COMMON_CODES_VIEW,
    M.APPROVALS, M.GOVERNANCE, M.AUDIT, M.VALIDATIONS, M.VALIDATION_DETAIL,
  ],
  STD_MANAGER: [
    M.DASHBOARD, M.EXPLORER, M.NEW_REQUEST, M.COMMON_CODES_VIEW,
    M.GOVERNANCE, M.AUDIT, M.VALIDATIONS, M.VALIDATION_DETAIL,
    M.ADMIN_COMMON_CODES,
  ],
  REQUESTER: [
    M.DASHBOARD, M.EXPLORER, M.NEW_REQUEST, M.COMMON_CODES_VIEW,
    M.AUDIT, M.VALIDATIONS,
  ],
  READ_ONLY: [
    M.DASHBOARD, M.EXPLORER, M.COMMON_CODES_VIEW, M.VALIDATIONS,
  ],
};
